spring:
  application:
    name: springb-demo
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:testdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

#management:
#  endpoints:
#    web:
#      exposure:
#        include: info, health, beans, env, metrics

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.mengliu.springbdemo.model
  configuration:
    map-underscore-to-camel-case: true


server:
  port: ${APP_PORT:8080}


